### ISSUE TITLE
An error occurred within SPCFileWriter

### ISSUE THREAD

**Issue by AnnNing** [WasatchPhotonics/SPyC_Writer#7]
```
from SPyC_Writer.SPCFileWriter import SPCFileWriter

writer = SPCFileWriter()
```

then

`Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from SPyC_Writer.SPCFileWriter import SPCFileWriter
  File "H:\python\SPyC_Writer-main\src\SPyC_Writer\SPCFileWriter.py", line 48, in <module>
    from .SPCHeader import SPCHeader
  File "H:\python\SPyC_Writer-main\src\SPyC_Writer\SPCHeader.py", line 16, in <module>
    class SPCHeader:
  File "H:\python\SPyC_Writer-main\src\SPyC_Writer\SPCHeader.py", line 41, in SPCHeader
    custom_axes: list[str] = field(default_factory=list) # (fcatxt)
TypeError: 'type' object is not subscriptable`

**Comment by AnnNing** [comment]
I add some code, it's ok now.

SPCFileWriter.py

add `from typing import List`
change `custom_units: list[str] = field(default_factory=list),` to `custom_units: List[str] = field(default_factory=list),`

SPCHeader.py

add `from typing import List`
change `custom_axes: list[str] = field(default_factory=list)` to `custom_axes: List[str] = field(default_factory=list)`
